
export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
  ADMISSION_OFFICER = 'ADMISSION_OFFICER',
  ACCOUNTANT = 'ACCOUNTANT'
}

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  TEACHER: 'TEACHER', 
  STUDENT: 'STUDENT',
  PARENT: 'PARENT',
  ADMISSION_OFFICER: 'ADMISSION_OFFICER',
  ACCOUNTANT: 'ACCOUNTANT'
} as const;